using RRCG;
using RRCGBuild;

namespace RRCGBuild
{
    public class AudioPort : AnyPort
    {
        public SFXConstantData SFXData;

        public static AudioPort AudioSFXConstant(string clipName)
        {
            return ChipBuilder.SFXConstant(new SFXConstantData(clipName));
        }

        public static AudioPort SFX_Adequate { get => CircuitBuilder.Singleton("SFX_Adequate", () => AudioSFXConstant("Adequate")); }
        public static AudioPort SFX_Amazing { get => CircuitBuilder.Singleton("SFX_Amazing", () => AudioSFXConstant("Amazing")); }
        public static AudioPort SFX_BeamGunDrop { get => CircuitBuilder.Singleton("SFX_BeamGunDrop", () => AudioSFXConstant("BeamGunDrop")); }
        public static AudioPort SFX_BeamGunPickup { get => CircuitBuilder.Singleton("SFX_BeamGunPickup", () => AudioSFXConstant("BeamGunPickup")); }
        public static AudioPort SFX_Beep { get => CircuitBuilder.Singleton("SFX_Beep", () => AudioSFXConstant("Beep")); }
        public static AudioPort SFX_BlueScores { get => CircuitBuilder.Singleton("SFX_BlueScores", () => AudioSFXConstant("BlueScores")); }
        public static AudioPort SFX_BlueWins { get => CircuitBuilder.Singleton("SFX_BlueWins", () => AudioSFXConstant("BlueWins")); }
        public static AudioPort SFX_BootUp { get => CircuitBuilder.Singleton("SFX_BootUp", () => AudioSFXConstant("BootUp")); }
        public static AudioPort SFX_BowlingStrike { get => CircuitBuilder.Singleton("SFX_BowlingStrike", () => AudioSFXConstant("BowlingStrike")); }
        public static AudioPort SFX_BowlingSweeper { get => CircuitBuilder.Singleton("SFX_BowlingSweeper", () => AudioSFXConstant("BowlingSweeper")); }
        public static AudioPort SFX_BowlingThud { get => CircuitBuilder.Singleton("SFX_BowlingThud", () => AudioSFXConstant("BowlingThud")); }
        public static AudioPort SFX_BroomHit01 { get => CircuitBuilder.Singleton("SFX_BroomHit01", () => AudioSFXConstant("BroomHit01")); }
        public static AudioPort SFX_BroomHit02 { get => CircuitBuilder.Singleton("SFX_BroomHit02", () => AudioSFXConstant("BroomHit02")); }
        public static AudioPort SFX_BroomPickup01 { get => CircuitBuilder.Singleton("SFX_BroomPickup01", () => AudioSFXConstant("BroomPickup01")); }
        public static AudioPort SFX_BroomPickup02 { get => CircuitBuilder.Singleton("SFX_BroomPickup02", () => AudioSFXConstant("BroomPickup02")); }
        public static AudioPort SFX_BroomSwing { get => CircuitBuilder.Singleton("SFX_BroomSwing", () => AudioSFXConstant("BroomSwing")); }
        public static AudioPort SFX_BucketHit { get => CircuitBuilder.Singleton("SFX_BucketHit", () => AudioSFXConstant("BucketHit")); }
        public static AudioPort SFX_ButtonDown { get => CircuitBuilder.Singleton("SFX_ButtonDown", () => AudioSFXConstant("ButtonDown")); }
        public static AudioPort SFX_ButtonUp { get => CircuitBuilder.Singleton("SFX_ButtonUp", () => AudioSFXConstant("ButtonUp")); }
        public static AudioPort SFX_Buzzer { get => CircuitBuilder.Singleton("SFX_Buzzer", () => AudioSFXConstant("Buzzer")); }
        public static AudioPort SFX_BuzzerShort { get => CircuitBuilder.Singleton("SFX_BuzzerShort", () => AudioSFXConstant("BuzzerShort")); }
        public static AudioPort SFX_CCCCannonFired { get => CircuitBuilder.Singleton("SFX_CCCCannonFired", () => AudioSFXConstant("CCCCannonFired")); }
        public static AudioPort SFX_CCCCannonImpact { get => CircuitBuilder.Singleton("SFX_CCCCannonImpact", () => AudioSFXConstant("CCCCannonImpact")); }
        public static AudioPort SFX_CCCCannonLit { get => CircuitBuilder.Singleton("SFX_CCCCannonLit", () => AudioSFXConstant("CCCCannonLit")); }
        public static AudioPort SFX_CCCCannonballIncoming { get => CircuitBuilder.Singleton("SFX_CCCCannonballIncoming", () => AudioSFXConstant("CCCCannonballIncoming")); }
        public static AudioPort SFX_CapturePointScore { get => CircuitBuilder.Singleton("SFX_CapturePointScore", () => AudioSFXConstant("CapturePointScore")); }
        public static AudioPort SFX_CardDeal { get => CircuitBuilder.Singleton("SFX_CardDeal", () => AudioSFXConstant("CardDeal")); }
        public static AudioPort SFX_CardShuffle { get => CircuitBuilder.Singleton("SFX_CardShuffle", () => AudioSFXConstant("CardShuffle")); }
        public static AudioPort SFX_CardSlide { get => CircuitBuilder.Singleton("SFX_CardSlide", () => AudioSFXConstant("CardSlide")); }
        public static AudioPort SFX_CardboardThud { get => CircuitBuilder.Singleton("SFX_CardboardThud", () => AudioSFXConstant("CardboardThud")); }
        public static AudioPort SFX_CashRegister { get => CircuitBuilder.Singleton("SFX_CashRegister", () => AudioSFXConstant("CashRegister")); }
        public static AudioPort SFX_Click { get => CircuitBuilder.Singleton("SFX_Click", () => AudioSFXConstant("Click")); }
        public static AudioPort SFX_Coach1 { get => CircuitBuilder.Singleton("SFX_Coach1", () => AudioSFXConstant("Coach1")); }
        public static AudioPort SFX_Coach2 { get => CircuitBuilder.Singleton("SFX_Coach2", () => AudioSFXConstant("Coach2")); }
        public static AudioPort SFX_Coach3 { get => CircuitBuilder.Singleton("SFX_Coach3", () => AudioSFXConstant("Coach3")); }
        public static AudioPort SFX_Coach4 { get => CircuitBuilder.Singleton("SFX_Coach4", () => AudioSFXConstant("Coach4")); }
        public static AudioPort SFX_Coach5 { get => CircuitBuilder.Singleton("SFX_Coach5", () => AudioSFXConstant("Coach5")); }
        public static AudioPort SFX_Coach6 { get => CircuitBuilder.Singleton("SFX_Coach6", () => AudioSFXConstant("Coach6")); }
        public static AudioPort SFX_Coach7 { get => CircuitBuilder.Singleton("SFX_Coach7", () => AudioSFXConstant("Coach7")); }
        public static AudioPort SFX_Coach8 { get => CircuitBuilder.Singleton("SFX_Coach8", () => AudioSFXConstant("Coach8")); }
        public static AudioPort SFX_Coach9 { get => CircuitBuilder.Singleton("SFX_Coach9", () => AudioSFXConstant("Coach9")); }
        public static AudioPort SFX_Coach10 { get => CircuitBuilder.Singleton("SFX_Coach10", () => AudioSFXConstant("Coach10")); }
        public static AudioPort SFX_Collectible { get => CircuitBuilder.Singleton("SFX_Collectible", () => AudioSFXConstant("Collectible")); }
        public static AudioPort SFX_ConsumableAppleBite { get => CircuitBuilder.Singleton("SFX_ConsumableAppleBite", () => AudioSFXConstant("ConsumableAppleBite")); }
        public static AudioPort SFX_ConsumableCakeBite01 { get => CircuitBuilder.Singleton("SFX_ConsumableCakeBite01", () => AudioSFXConstant("ConsumableCakeBite01")); }
        public static AudioPort SFX_ConsumableCakeBite02 { get => CircuitBuilder.Singleton("SFX_ConsumableCakeBite02", () => AudioSFXConstant("ConsumableCakeBite02")); }
        public static AudioPort SFX_ConsumableCakeBite03 { get => CircuitBuilder.Singleton("SFX_ConsumableCakeBite03", () => AudioSFXConstant("ConsumableCakeBite03")); }
        public static AudioPort SFX_ConsumablePizzaBite { get => CircuitBuilder.Singleton("SFX_ConsumablePizzaBite", () => AudioSFXConstant("ConsumablePizzaBite")); }
        public static AudioPort SFX_ConsumablePopcornBite01 { get => CircuitBuilder.Singleton("SFX_ConsumablePopcornBite01", () => AudioSFXConstant("ConsumablePopcornBite01")); }
        public static AudioPort SFX_ConsumablePopcornBite02 { get => CircuitBuilder.Singleton("SFX_ConsumablePopcornBite02", () => AudioSFXConstant("ConsumablePopcornBite02")); }
        public static AudioPort SFX_ConsumableRootBeerGlug { get => CircuitBuilder.Singleton("SFX_ConsumableRootBeerGlug", () => AudioSFXConstant("ConsumableRootBeerGlug")); }
        public static AudioPort SFX_CountdownStinger { get => CircuitBuilder.Singleton("SFX_CountdownStinger", () => AudioSFXConstant("CountdownStinger")); }
        public static AudioPort SFX_CountdownTick { get => CircuitBuilder.Singleton("SFX_CountdownTick", () => AudioSFXConstant("CountdownTick")); }
        public static AudioPort SFX_Cows { get => CircuitBuilder.Singleton("SFX_Cows", () => AudioSFXConstant("Cows")); }
        public static AudioPort SFX_CrowdAww { get => CircuitBuilder.Singleton("SFX_CrowdAww", () => AudioSFXConstant("CrowdAww")); }
        public static AudioPort SFX_CrowdCheer { get => CircuitBuilder.Singleton("SFX_CrowdCheer", () => AudioSFXConstant("CrowdCheer")); }
        public static AudioPort SFX_CrowdLaughing { get => CircuitBuilder.Singleton("SFX_CrowdLaughing", () => AudioSFXConstant("CrowdLaughing")); }
        public static AudioPort SFX_CrowdOoooo { get => CircuitBuilder.Singleton("SFX_CrowdOoooo", () => AudioSFXConstant("CrowdOoooo")); }
        public static AudioPort SFX_CutlassHeavyEnemyHit01 { get => CircuitBuilder.Singleton("SFX_CutlassHeavyEnemyHit01", () => AudioSFXConstant("CutlassHeavyEnemyHit01")); }
        public static AudioPort SFX_CutlassHeavyEnemyHit02 { get => CircuitBuilder.Singleton("SFX_CutlassHeavyEnemyHit02", () => AudioSFXConstant("CutlassHeavyEnemyHit02")); }
        public static AudioPort SFX_CutlassHeavyEnemyHit03 { get => CircuitBuilder.Singleton("SFX_CutlassHeavyEnemyHit03", () => AudioSFXConstant("CutlassHeavyEnemyHit03")); }
        public static AudioPort SFX_CutlassHit01 { get => CircuitBuilder.Singleton("SFX_CutlassHit01", () => AudioSFXConstant("CutlassHit01")); }
        public static AudioPort SFX_CutlassHit02 { get => CircuitBuilder.Singleton("SFX_CutlassHit02", () => AudioSFXConstant("CutlassHit02")); }
        public static AudioPort SFX_CutlassLightEnemyHit01 { get => CircuitBuilder.Singleton("SFX_CutlassLightEnemyHit01", () => AudioSFXConstant("CutlassLightEnemyHit01")); }
        public static AudioPort SFX_CutlassLightEnemyHit02 { get => CircuitBuilder.Singleton("SFX_CutlassLightEnemyHit02", () => AudioSFXConstant("CutlassLightEnemyHit02")); }
        public static AudioPort SFX_CutlassParry01 { get => CircuitBuilder.Singleton("SFX_CutlassParry01", () => AudioSFXConstant("CutlassParry01")); }
        public static AudioPort SFX_CutlassParry02 { get => CircuitBuilder.Singleton("SFX_CutlassParry02", () => AudioSFXConstant("CutlassParry02")); }
        public static AudioPort SFX_CutlassParry03 { get => CircuitBuilder.Singleton("SFX_CutlassParry03", () => AudioSFXConstant("CutlassParry03")); }
        public static AudioPort SFX_CutlassPickup { get => CircuitBuilder.Singleton("SFX_CutlassPickup", () => AudioSFXConstant("CutlassPickup")); }
        public static AudioPort SFX_CutlassSwing01 { get => CircuitBuilder.Singleton("SFX_CutlassSwing01", () => AudioSFXConstant("CutlassSwing01")); }
        public static AudioPort SFX_CutlassSwing02 { get => CircuitBuilder.Singleton("SFX_CutlassSwing02", () => AudioSFXConstant("CutlassSwing02")); }
        public static AudioPort SFX_CutlassSwing03 { get => CircuitBuilder.Singleton("SFX_CutlassSwing03", () => AudioSFXConstant("CutlassSwing03")); }
        public static AudioPort SFX_DartHit { get => CircuitBuilder.Singleton("SFX_DartHit", () => AudioSFXConstant("DartHit")); }
        public static AudioPort SFX_DefaultFoostep01 { get => CircuitBuilder.Singleton("SFX_DefaultFoostep01", () => AudioSFXConstant("DefaultFoostep01")); }
        public static AudioPort SFX_DefaultFootstep02 { get => CircuitBuilder.Singleton("SFX_DefaultFootstep02", () => AudioSFXConstant("DefaultFootstep02")); }
        public static AudioPort SFX_DefaultFootstep03 { get => CircuitBuilder.Singleton("SFX_DefaultFootstep03", () => AudioSFXConstant("DefaultFootstep03")); }
        public static AudioPort SFX_DefaultFootstepProne01 { get => CircuitBuilder.Singleton("SFX_DefaultFootstepProne01", () => AudioSFXConstant("DefaultFootstepProne01")); }
        public static AudioPort SFX_DefaultFootstepProne02 { get => CircuitBuilder.Singleton("SFX_DefaultFootstepProne02", () => AudioSFXConstant("DefaultFootstepProne02")); }
        public static AudioPort SFX_DefaultJump { get => CircuitBuilder.Singleton("SFX_DefaultJump", () => AudioSFXConstant("DefaultJump")); }
        public static AudioPort SFX_DiceRoll { get => CircuitBuilder.Singleton("SFX_DiceRoll", () => AudioSFXConstant("DiceRoll")); }
        public static AudioPort SFX_Ding { get => CircuitBuilder.Singleton("SFX_Ding", () => AudioSFXConstant("Ding")); }
        public static AudioPort SFX_DingDing { get => CircuitBuilder.Singleton("SFX_DingDing", () => AudioSFXConstant("DingDing")); }
        public static AudioPort SFX_DiscHit { get => CircuitBuilder.Singleton("SFX_DiscHit", () => AudioSFXConstant("DiscHit")); }
        public static AudioPort SFX_DodgeballBounce { get => CircuitBuilder.Singleton("SFX_DodgeballBounce", () => AudioSFXConstant("DodgeballBounce")); }
        public static AudioPort SFX_DodgeballPlayerHit { get => CircuitBuilder.Singleton("SFX_DodgeballPlayerHit", () => AudioSFXConstant("DodgeballPlayerHit")); }
        public static AudioPort SFX_Drawer { get => CircuitBuilder.Singleton("SFX_Drawer", () => AudioSFXConstant("Drawer")); }
        public static AudioPort SFX_ElectronicsMove { get => CircuitBuilder.Singleton("SFX_ElectronicsMove", () => AudioSFXConstant("ElectronicsMove")); }
        public static AudioPort SFX_ElectronicsWarmUp { get => CircuitBuilder.Singleton("SFX_ElectronicsWarmUp", () => AudioSFXConstant("ElectronicsWarmUp")); }
        public static AudioPort SFX_Equipment { get => CircuitBuilder.Singleton("SFX_Equipment", () => AudioSFXConstant("Equipment")); }
        public static AudioPort SFX_Explosion { get => CircuitBuilder.Singleton("SFX_Explosion", () => AudioSFXConstant("Explosion")); }
        public static AudioPort SFX_Failure { get => CircuitBuilder.Singleton("SFX_Failure", () => AudioSFXConstant("Failure")); }
        public static AudioPort SFX_Firework { get => CircuitBuilder.Singleton("SFX_Firework", () => AudioSFXConstant("Firework")); }
        public static AudioPort SFX_FryingPanEnvironmentHit { get => CircuitBuilder.Singleton("SFX_FryingPanEnvironmentHit", () => AudioSFXConstant("FryingPanEnvironmentHit")); }
        public static AudioPort SFX_FryingPanHit01 { get => CircuitBuilder.Singleton("SFX_FryingPanHit01", () => AudioSFXConstant("FryingPanHit01")); }
        public static AudioPort SFX_FryingPanHit02 { get => CircuitBuilder.Singleton("SFX_FryingPanHit02", () => AudioSFXConstant("FryingPanHit02")); }
        public static AudioPort SFX_FryingPanHit03 { get => CircuitBuilder.Singleton("SFX_FryingPanHit03", () => AudioSFXConstant("FryingPanHit03")); }
        public static AudioPort SFX_FryingPanPickup { get => CircuitBuilder.Singleton("SFX_FryingPanPickup", () => AudioSFXConstant("FryingPanPickup")); }
        public static AudioPort SFX_FryingPanSwing01 { get => CircuitBuilder.Singleton("SFX_FryingPanSwing01", () => AudioSFXConstant("FryingPanSwing01")); }
        public static AudioPort SFX_FryingPanSwing02 { get => CircuitBuilder.Singleton("SFX_FryingPanSwing02", () => AudioSFXConstant("FryingPanSwing02")); }
        public static AudioPort SFX_GTRoomClear { get => CircuitBuilder.Singleton("SFX_GTRoomClear", () => AudioSFXConstant("GTRoomClear")); }
        public static AudioPort SFX_GameOn { get => CircuitBuilder.Singleton("SFX_GameOn", () => AudioSFXConstant("GameOn")); }
        public static AudioPort SFX_GameOver { get => CircuitBuilder.Singleton("SFX_GameOver", () => AudioSFXConstant("GameOver")); }
        public static AudioPort SFX_GameOverBell { get => CircuitBuilder.Singleton("SFX_GameOverBell", () => AudioSFXConstant("GameOverBell")); }
        public static AudioPort SFX_GlassBreak01 { get => CircuitBuilder.Singleton("SFX_GlassBreak01", () => AudioSFXConstant("GlassBreak01")); }
        public static AudioPort SFX_GlassBreak02 { get => CircuitBuilder.Singleton("SFX_GlassBreak02", () => AudioSFXConstant("GlassBreak02")); }
        public static AudioPort SFX_Goal { get => CircuitBuilder.Singleton("SFX_Goal", () => AudioSFXConstant("Goal")); }
        public static AudioPort SFX_Goats { get => CircuitBuilder.Singleton("SFX_Goats", () => AudioSFXConstant("Goats")); }
        public static AudioPort SFX_GoldDropped { get => CircuitBuilder.Singleton("SFX_GoldDropped", () => AudioSFXConstant("GoldDropped")); }
        public static AudioPort SFX_GoldPickup01 { get => CircuitBuilder.Singleton("SFX_GoldPickup01", () => AudioSFXConstant("GoldPickup01")); }
        public static AudioPort SFX_GoldPickup02 { get => CircuitBuilder.Singleton("SFX_GoldPickup02", () => AudioSFXConstant("GoldPickup02")); }
        public static AudioPort SFX_GolfClap { get => CircuitBuilder.Singleton("SFX_GolfClap", () => AudioSFXConstant("GolfClap")); }
        public static AudioPort SFX_GoodGame { get => CircuitBuilder.Singleton("SFX_GoodGame", () => AudioSFXConstant("GoodGame")); }
        public static AudioPort SFX_HeartbeatDown { get => CircuitBuilder.Singleton("SFX_HeartbeatDown", () => AudioSFXConstant("HeartbeatDown")); }
        public static AudioPort SFX_HeartbeatUp { get => CircuitBuilder.Singleton("SFX_HeartbeatUp", () => AudioSFXConstant("HeartbeatUp")); }
        public static AudioPort SFX_Henhouse { get => CircuitBuilder.Singleton("SFX_Henhouse", () => AudioSFXConstant("Henhouse")); }
        public static AudioPort SFX_Hit { get => CircuitBuilder.Singleton("SFX_Hit", () => AudioSFXConstant("Hit")); }
        public static AudioPort SFX_HolsterAttach { get => CircuitBuilder.Singleton("SFX_HolsterAttach", () => AudioSFXConstant("HolsterAttach")); }
        public static AudioPort SFX_HolsterDetach { get => CircuitBuilder.Singleton("SFX_HolsterDetach", () => AudioSFXConstant("HolsterDetach")); }
        public static AudioPort SFX_Horn { get => CircuitBuilder.Singleton("SFX_Horn", () => AudioSFXConstant("Horn")); }
        public static AudioPort SFX_Horse { get => CircuitBuilder.Singleton("SFX_Horse", () => AudioSFXConstant("Horse")); }
        public static AudioPort SFX_KOColaTabOpened { get => CircuitBuilder.Singleton("SFX_KOColaTabOpened", () => AudioSFXConstant("KOColaTabOpened")); }
        public static AudioPort SFX_KioskButton { get => CircuitBuilder.Singleton("SFX_KioskButton", () => AudioSFXConstant("KioskButton")); }
        public static AudioPort SFX_LaserTagCrit { get => CircuitBuilder.Singleton("SFX_LaserTagCrit", () => AudioSFXConstant("LaserTagCrit")); }
        public static AudioPort SFX_LaserTagDamage { get => CircuitBuilder.Singleton("SFX_LaserTagDamage", () => AudioSFXConstant("LaserTagDamage")); }
        public static AudioPort SFX_LaserTagDetonation { get => CircuitBuilder.Singleton("SFX_LaserTagDetonation", () => AudioSFXConstant("LaserTagDetonation")); }
        public static AudioPort SFX_LaserTagNotification { get => CircuitBuilder.Singleton("SFX_LaserTagNotification", () => AudioSFXConstant("LaserTagNotification")); }
        public static AudioPort SFX_LaserTagOut { get => CircuitBuilder.Singleton("SFX_LaserTagOut", () => AudioSFXConstant("LaserTagOut")); }
        public static AudioPort SFX_LatchGrab { get => CircuitBuilder.Singleton("SFX_LatchGrab", () => AudioSFXConstant("LatchGrab")); }
        public static AudioPort SFX_LiquidPour { get => CircuitBuilder.Singleton("SFX_LiquidPour", () => AudioSFXConstant("LiquidPour")); }
        public static AudioPort SFX_MeleeHit { get => CircuitBuilder.Singleton("SFX_MeleeHit", () => AudioSFXConstant("MeleeHit")); }
        public static AudioPort SFX_MenuClick01 { get => CircuitBuilder.Singleton("SFX_MenuClick01", () => AudioSFXConstant("MenuClick01")); }
        public static AudioPort SFX_MenuClick02 { get => CircuitBuilder.Singleton("SFX_MenuClick02", () => AudioSFXConstant("MenuClick02")); }
        public static AudioPort SFX_MetalClunk { get => CircuitBuilder.Singleton("SFX_MetalClunk", () => AudioSFXConstant("MetalClunk")); }
        public static AudioPort SFX_MetalClunkLight { get => CircuitBuilder.Singleton("SFX_MetalClunkLight", () => AudioSFXConstant("MetalClunkLight")); }
        public static AudioPort SFX_MetalCreak01 { get => CircuitBuilder.Singleton("SFX_MetalCreak01", () => AudioSFXConstant("MetalCreak01")); }
        public static AudioPort SFX_MetalCreak02 { get => CircuitBuilder.Singleton("SFX_MetalCreak02", () => AudioSFXConstant("MetalCreak02")); }
        public static AudioPort SFX_MicrophoneFeedback { get => CircuitBuilder.Singleton("SFX_MicrophoneFeedback", () => AudioSFXConstant("MicrophoneFeedback")); }
        public static AudioPort SFX_MicrophoneTap { get => CircuitBuilder.Singleton("SFX_MicrophoneTap", () => AudioSFXConstant("MicrophoneTap")); }
        public static AudioPort SFX_OarHit { get => CircuitBuilder.Singleton("SFX_OarHit", () => AudioSFXConstant("OarHit")); }
        public static AudioPort SFX_OarSwing { get => CircuitBuilder.Singleton("SFX_OarSwing", () => AudioSFXConstant("OarSwing")); }
        public static AudioPort SFX_PaintmineArm { get => CircuitBuilder.Singleton("SFX_PaintmineArm", () => AudioSFXConstant("PaintmineArm")); }
        public static AudioPort SFX_PaintmineAttach { get => CircuitBuilder.Singleton("SFX_PaintmineAttach", () => AudioSFXConstant("PaintmineAttach")); }
        public static AudioPort SFX_PaintmineDetonate { get => CircuitBuilder.Singleton("SFX_PaintmineDetonate", () => AudioSFXConstant("PaintmineDetonate")); }
        public static AudioPort SFX_PaintmineTrip { get => CircuitBuilder.Singleton("SFX_PaintmineTrip", () => AudioSFXConstant("PaintmineTrip")); }
        public static AudioPort SFX_PitchforkHeavyHit { get => CircuitBuilder.Singleton("SFX_PitchforkHeavyHit", () => AudioSFXConstant("PitchforkHeavyHit")); }
        public static AudioPort SFX_PitchforkLightHit { get => CircuitBuilder.Singleton("SFX_PitchforkLightHit", () => AudioSFXConstant("PitchforkLightHit")); }
        public static AudioPort SFX_PitchforkPickup { get => CircuitBuilder.Singleton("SFX_PitchforkPickup", () => AudioSFXConstant("PitchforkPickup")); }
        public static AudioPort SFX_PitchforkSwing { get => CircuitBuilder.Singleton("SFX_PitchforkSwing", () => AudioSFXConstant("PitchforkSwing")); }
        public static AudioPort SFX_PointBlip { get => CircuitBuilder.Singleton("SFX_PointBlip", () => AudioSFXConstant("PointBlip")); }
        public static AudioPort SFX_PointCaptured { get => CircuitBuilder.Singleton("SFX_PointCaptured", () => AudioSFXConstant("PointCaptured")); }
        public static AudioPort SFX_PokerChipClack { get => CircuitBuilder.Singleton("SFX_PokerChipClack", () => AudioSFXConstant("PokerChipClack")); }
        public static AudioPort SFX_PoolBallEnterPocket { get => CircuitBuilder.Singleton("SFX_PoolBallEnterPocket", () => AudioSFXConstant("PoolBallEnterPocket")); }
        public static AudioPort SFX_PoolBallHitsBall { get => CircuitBuilder.Singleton("SFX_PoolBallHitsBall", () => AudioSFXConstant("PoolBallHitsBall")); }
        public static AudioPort SFX_PoolBallHitsCushion { get => CircuitBuilder.Singleton("SFX_PoolBallHitsCushion", () => AudioSFXConstant("PoolBallHitsCushion")); }
        public static AudioPort SFX_PoolCueHitsBall { get => CircuitBuilder.Singleton("SFX_PoolCueHitsBall", () => AudioSFXConstant("PoolCueHitsBall")); }
        public static AudioPort SFX_PoolCueHitsFloor { get => CircuitBuilder.Singleton("SFX_PoolCueHitsFloor", () => AudioSFXConstant("PoolCueHitsFloor")); }
        public static AudioPort SFX_PowerMissileExplode { get => CircuitBuilder.Singleton("SFX_PowerMissileExplode", () => AudioSFXConstant("PowerMissileExplode")); }
        public static AudioPort SFX_PowerMissileFire { get => CircuitBuilder.Singleton("SFX_PowerMissileFire", () => AudioSFXConstant("PowerMissileFire")); }
        public static AudioPort SFX_PowerMissileImpact { get => CircuitBuilder.Singleton("SFX_PowerMissileImpact", () => AudioSFXConstant("PowerMissileImpact")); }
        public static AudioPort SFX_Punch1 { get => CircuitBuilder.Singleton("SFX_Punch1", () => AudioSFXConstant("Punch1")); }
        public static AudioPort SFX_Punch2 { get => CircuitBuilder.Singleton("SFX_Punch2", () => AudioSFXConstant("Punch2")); }
        public static AudioPort SFX_RakeHeavyHit { get => CircuitBuilder.Singleton("SFX_RakeHeavyHit", () => AudioSFXConstant("RakeHeavyHit")); }
        public static AudioPort SFX_RakeLightHit { get => CircuitBuilder.Singleton("SFX_RakeLightHit", () => AudioSFXConstant("RakeLightHit")); }
        public static AudioPort SFX_RakePickup { get => CircuitBuilder.Singleton("SFX_RakePickup", () => AudioSFXConstant("RakePickup")); }
        public static AudioPort SFX_RakeSwing { get => CircuitBuilder.Singleton("SFX_RakeSwing", () => AudioSFXConstant("RakeSwing")); }
        public static AudioPort SFX_Rattlesnake { get => CircuitBuilder.Singleton("SFX_Rattlesnake", () => AudioSFXConstant("Rattlesnake")); }
        public static AudioPort SFX_ReadyToStart { get => CircuitBuilder.Singleton("SFX_ReadyToStart", () => AudioSFXConstant("ReadyToStart")); }
        public static AudioPort SFX_RedScores { get => CircuitBuilder.Singleton("SFX_RedScores", () => AudioSFXConstant("RedScores")); }
        public static AudioPort SFX_RedWins { get => CircuitBuilder.Singleton("SFX_RedWins", () => AudioSFXConstant("RedWins")); }
        public static AudioPort SFX_Revive { get => CircuitBuilder.Singleton("SFX_Revive", () => AudioSFXConstant("Revive")); }
        public static AudioPort SFX_RezIn { get => CircuitBuilder.Singleton("SFX_RezIn", () => AudioSFXConstant("RezIn")); }
        public static AudioPort SFX_Score { get => CircuitBuilder.Singleton("SFX_Score", () => AudioSFXConstant("Score")); }
        public static AudioPort SFX_ShareCamCountdownTick { get => CircuitBuilder.Singleton("SFX_ShareCamCountdownTick", () => AudioSFXConstant("ShareCamCountdownTick")); }
        public static AudioPort SFX_ShareCamPrint { get => CircuitBuilder.Singleton("SFX_ShareCamPrint", () => AudioSFXConstant("ShareCamPrint")); }
        public static AudioPort SFX_ShareCamShutter { get => CircuitBuilder.Singleton("SFX_ShareCamShutter", () => AudioSFXConstant("ShareCamShutter")); }
        public static AudioPort SFX_ShareCamSuccess { get => CircuitBuilder.Singleton("SFX_ShareCamSuccess", () => AudioSFXConstant("ShareCamSuccess")); }
        public static AudioPort SFX_ShieldHit { get => CircuitBuilder.Singleton("SFX_ShieldHit", () => AudioSFXConstant("ShieldHit")); }
        public static AudioPort SFX_ShovelBash01 { get => CircuitBuilder.Singleton("SFX_ShovelBash01", () => AudioSFXConstant("ShovelBash01")); }
        public static AudioPort SFX_ShovelBash02 { get => CircuitBuilder.Singleton("SFX_ShovelBash02", () => AudioSFXConstant("ShovelBash02")); }
        public static AudioPort SFX_ShovelHeavyHit { get => CircuitBuilder.Singleton("SFX_ShovelHeavyHit", () => AudioSFXConstant("ShovelHeavyHit")); }
        public static AudioPort SFX_ShovelLightHit { get => CircuitBuilder.Singleton("SFX_ShovelLightHit", () => AudioSFXConstant("ShovelLightHit")); }
        public static AudioPort SFX_ShovelPickup { get => CircuitBuilder.Singleton("SFX_ShovelPickup", () => AudioSFXConstant("ShovelPickup")); }
        public static AudioPort SFX_ShovelSwing { get => CircuitBuilder.Singleton("SFX_ShovelSwing", () => AudioSFXConstant("ShovelSwing")); }
        public static AudioPort SFX_SmallExplosion1 { get => CircuitBuilder.Singleton("SFX_SmallExplosion1", () => AudioSFXConstant("SmallExplosion1")); }
        public static AudioPort SFX_SmallExplosion2 { get => CircuitBuilder.Singleton("SFX_SmallExplosion2", () => AudioSFXConstant("SmallExplosion2")); }
        public static AudioPort SFX_SnareDrum { get => CircuitBuilder.Singleton("SFX_SnareDrum", () => AudioSFXConstant("SnareDrum")); }
        public static AudioPort SFX_SoccerBallHeavy { get => CircuitBuilder.Singleton("SFX_SoccerBallHeavy", () => AudioSFXConstant("SoccerBallHeavy")); }
        public static AudioPort SFX_SoccerBallHitHeavy { get => CircuitBuilder.Singleton("SFX_SoccerBallHitHeavy", () => AudioSFXConstant("SoccerBallHitHeavy")); }
        public static AudioPort SFX_SoccerBallHitLight { get => CircuitBuilder.Singleton("SFX_SoccerBallHitLight", () => AudioSFXConstant("SoccerBallHitLight")); }
        public static AudioPort SFX_Sparkle { get => CircuitBuilder.Singleton("SFX_Sparkle", () => AudioSFXConstant("Sparkle")); }
        public static AudioPort SFX_Splash { get => CircuitBuilder.Singleton("SFX_Splash", () => AudioSFXConstant("Splash")); }
        public static AudioPort SFX_Springboard { get => CircuitBuilder.Singleton("SFX_Springboard", () => AudioSFXConstant("Springboard")); }
        public static AudioPort SFX_SqueakyFishEnvironmentHit { get => CircuitBuilder.Singleton("SFX_SqueakyFishEnvironmentHit", () => AudioSFXConstant("SqueakyFishEnvironmentHit")); }
        public static AudioPort SFX_SqueakyFishHit01 { get => CircuitBuilder.Singleton("SFX_SqueakyFishHit01", () => AudioSFXConstant("SqueakyFishHit01")); }
        public static AudioPort SFX_SqueakyFishHit02 { get => CircuitBuilder.Singleton("SFX_SqueakyFishHit02", () => AudioSFXConstant("SqueakyFishHit02")); }
        public static AudioPort SFX_SqueakyFishHit03 { get => CircuitBuilder.Singleton("SFX_SqueakyFishHit03", () => AudioSFXConstant("SqueakyFishHit03")); }
        public static AudioPort SFX_SqueakyFishHit04 { get => CircuitBuilder.Singleton("SFX_SqueakyFishHit04", () => AudioSFXConstant("SqueakyFishHit04")); }
        public static AudioPort SFX_SqueakyFishPickup { get => CircuitBuilder.Singleton("SFX_SqueakyFishPickup", () => AudioSFXConstant("SqueakyFishPickup")); }
        public static AudioPort SFX_SqueakyFishSwing01 { get => CircuitBuilder.Singleton("SFX_SqueakyFishSwing01", () => AudioSFXConstant("SqueakyFishSwing01")); }
        public static AudioPort SFX_SqueakyFishSwing02 { get => CircuitBuilder.Singleton("SFX_SqueakyFishSwing02", () => AudioSFXConstant("SqueakyFishSwing02")); }
        public static AudioPort SFX_StickyNote { get => CircuitBuilder.Singleton("SFX_StickyNote", () => AudioSFXConstant("StickyNote")); }
        public static AudioPort SFX_StoolHit { get => CircuitBuilder.Singleton("SFX_StoolHit", () => AudioSFXConstant("StoolHit")); }
        public static AudioPort SFX_StoolPickup { get => CircuitBuilder.Singleton("SFX_StoolPickup", () => AudioSFXConstant("StoolPickup")); }
        public static AudioPort SFX_StoolShatter { get => CircuitBuilder.Singleton("SFX_StoolShatter", () => AudioSFXConstant("StoolShatter")); }
        public static AudioPort SFX_StuntrunnerCountdown1 { get => CircuitBuilder.Singleton("SFX_StuntrunnerCountdown1", () => AudioSFXConstant("StuntrunnerCountdown1")); }
        public static AudioPort SFX_StuntrunnerCountdown2 { get => CircuitBuilder.Singleton("SFX_StuntrunnerCountdown2", () => AudioSFXConstant("StuntrunnerCountdown2")); }
        public static AudioPort SFX_StuntrunnerCountdown3 { get => CircuitBuilder.Singleton("SFX_StuntrunnerCountdown3", () => AudioSFXConstant("StuntrunnerCountdown3")); }
        public static AudioPort SFX_StuntrunnerGetReady { get => CircuitBuilder.Singleton("SFX_StuntrunnerGetReady", () => AudioSFXConstant("StuntrunnerGetReady")); }
        public static AudioPort SFX_StuntrunnerGo { get => CircuitBuilder.Singleton("SFX_StuntrunnerGo", () => AudioSFXConstant("StuntrunnerGo")); }
        public static AudioPort SFX_SubsonicBoom { get => CircuitBuilder.Singleton("SFX_SubsonicBoom", () => AudioSFXConstant("SubsonicBoom")); }
        public static AudioPort SFX_SwordEnvironmentHit { get => CircuitBuilder.Singleton("SFX_SwordEnvironmentHit", () => AudioSFXConstant("SwordEnvironmentHit")); }
        public static AudioPort SFX_SwordHeavyEnemyHit { get => CircuitBuilder.Singleton("SFX_SwordHeavyEnemyHit", () => AudioSFXConstant("SwordHeavyEnemyHit")); }
        public static AudioPort SFX_SwordShieldHit { get => CircuitBuilder.Singleton("SFX_SwordShieldHit", () => AudioSFXConstant("SwordShieldHit")); }
        public static AudioPort SFX_TennisBallImpact { get => CircuitBuilder.Singleton("SFX_TennisBallImpact", () => AudioSFXConstant("TennisBallImpact")); }
        public static AudioPort SFX_Thud { get => CircuitBuilder.Singleton("SFX_Thud", () => AudioSFXConstant("Thud")); }
        public static AudioPort SFX_TieGame { get => CircuitBuilder.Singleton("SFX_TieGame", () => AudioSFXConstant("TieGame")); }
        public static AudioPort SFX_TiresScreeching { get => CircuitBuilder.Singleton("SFX_TiresScreeching", () => AudioSFXConstant("TiresScreeching")); }
        public static AudioPort SFX_ToggleButtonOFF { get => CircuitBuilder.Singleton("SFX_ToggleButtonOFF", () => AudioSFXConstant("ToggleButtonOFF")); }
        public static AudioPort SFX_ToggleButtonON { get => CircuitBuilder.Singleton("SFX_ToggleButtonON", () => AudioSFXConstant("ToggleButtonON")); }
        public static AudioPort SFX_TorchPickup { get => CircuitBuilder.Singleton("SFX_TorchPickup", () => AudioSFXConstant("TorchPickup")); }
        public static AudioPort SFX_TorchSwing { get => CircuitBuilder.Singleton("SFX_TorchSwing", () => AudioSFXConstant("TorchSwing")); }
        public static AudioPort SFX_TrainBell { get => CircuitBuilder.Singleton("SFX_TrainBell", () => AudioSFXConstant("TrainBell")); }
        public static AudioPort SFX_TriggerMisfire { get => CircuitBuilder.Singleton("SFX_TriggerMisfire", () => AudioSFXConstant("TriggerMisfire")); }
        public static AudioPort SFX_UILevelUp { get => CircuitBuilder.Singleton("SFX_UILevelUp", () => AudioSFXConstant("UILevelUp")); }
        public static AudioPort SFX_UIScore01 { get => CircuitBuilder.Singleton("SFX_UIScore01", () => AudioSFXConstant("UIScore01")); }
        public static AudioPort SFX_UIScore02 { get => CircuitBuilder.Singleton("SFX_UIScore02", () => AudioSFXConstant("UIScore02")); }
        public static AudioPort SFX_UIScore03 { get => CircuitBuilder.Singleton("SFX_UIScore03", () => AudioSFXConstant("UIScore03")); }
        public static AudioPort SFX_UIScore04 { get => CircuitBuilder.Singleton("SFX_UIScore04", () => AudioSFXConstant("UIScore04")); }
        public static AudioPort SFX_UIXP01 { get => CircuitBuilder.Singleton("SFX_UIXP01", () => AudioSFXConstant("UIXP01")); }
        public static AudioPort SFX_UIXP02 { get => CircuitBuilder.Singleton("SFX_UIXP02", () => AudioSFXConstant("UIXP02")); }
        public static AudioPort SFX_UIXP03 { get => CircuitBuilder.Singleton("SFX_UIXP03", () => AudioSFXConstant("UIXP03")); }
        public static AudioPort SFX_WalkieNotification { get => CircuitBuilder.Singleton("SFX_WalkieNotification", () => AudioSFXConstant("WalkieNotification")); }
        public static AudioPort SFX_WallSmack { get => CircuitBuilder.Singleton("SFX_WallSmack", () => AudioSFXConstant("WallSmack")); }
        public static AudioPort SFX_WatchButtonDown { get => CircuitBuilder.Singleton("SFX_WatchButtonDown", () => AudioSFXConstant("WatchButtonDown")); }
        public static AudioPort SFX_WatchButtonUp { get => CircuitBuilder.Singleton("SFX_WatchButtonUp", () => AudioSFXConstant("WatchButtonUp")); }
        public static AudioPort SFX_WatchOpen { get => CircuitBuilder.Singleton("SFX_WatchOpen", () => AudioSFXConstant("WatchOpen")); }
        public static AudioPort SFX_WaterGulp { get => CircuitBuilder.Singleton("SFX_WaterGulp", () => AudioSFXConstant("WaterGulp")); }
        public static AudioPort SFX_WaterSplash { get => CircuitBuilder.Singleton("SFX_WaterSplash", () => AudioSFXConstant("WaterSplash")); }
        public static AudioPort SFX_WhipHeavyThrow { get => CircuitBuilder.Singleton("SFX_WhipHeavyThrow", () => AudioSFXConstant("WhipHeavyThrow")); }
        public static AudioPort SFX_WhipLightThrow { get => CircuitBuilder.Singleton("SFX_WhipLightThrow", () => AudioSFXConstant("WhipLightThrow")); }
        public static AudioPort SFX_WhipPickup { get => CircuitBuilder.Singleton("SFX_WhipPickup", () => AudioSFXConstant("WhipPickup")); }
        public static AudioPort SFX_WhipPrime { get => CircuitBuilder.Singleton("SFX_WhipPrime", () => AudioSFXConstant("WhipPrime")); }
        public static AudioPort SFX_WhipTraversalHooked { get => CircuitBuilder.Singleton("SFX_WhipTraversalHooked", () => AudioSFXConstant("WhipTraversalHooked")); }
        public static AudioPort SFX_WhipTraversalTeleport { get => CircuitBuilder.Singleton("SFX_WhipTraversalTeleport", () => AudioSFXConstant("WhipTraversalTeleport")); }
        public static AudioPort SFX_WhipCrackHeavy { get => CircuitBuilder.Singleton("SFX_WhipCrackHeavy", () => AudioSFXConstant("WhipCrackHeavy")); }
        public static AudioPort SFX_WhipCrackLight01 { get => CircuitBuilder.Singleton("SFX_WhipCrackLight01", () => AudioSFXConstant("WhipCrackLight01")); }
        public static AudioPort SFX_WhipCrackLight02 { get => CircuitBuilder.Singleton("SFX_WhipCrackLight02", () => AudioSFXConstant("WhipCrackLight02")); }
        public static AudioPort SFX_Whistle01 { get => CircuitBuilder.Singleton("SFX_Whistle01", () => AudioSFXConstant("Whistle01")); }
        public static AudioPort SFX_Whistle02 { get => CircuitBuilder.Singleton("SFX_Whistle02", () => AudioSFXConstant("Whistle02")); }
        public static AudioPort SFX_WhistleDown { get => CircuitBuilder.Singleton("SFX_WhistleDown", () => AudioSFXConstant("WhistleDown")); }
        public static AudioPort SFX_WhistleUp { get => CircuitBuilder.Singleton("SFX_WhistleUp", () => AudioSFXConstant("WhistleUp")); }
        public static AudioPort SFX_Whoosh1 { get => CircuitBuilder.Singleton("SFX_Whoosh1", () => AudioSFXConstant("Whoosh1")); }
        public static AudioPort SFX_Whoosh2 { get => CircuitBuilder.Singleton("SFX_Whoosh2", () => AudioSFXConstant("Whoosh2")); }
        public static AudioPort SFX_YouWin { get => CircuitBuilder.Singleton("SFX_YouWin", () => AudioSFXConstant("YouWin")); }
        public static AudioPort SFX_Zipper01 { get => CircuitBuilder.Singleton("SFX_Zipper01", () => AudioSFXConstant("Zipper01")); }
        public static AudioPort SFX_Zipper02 { get => CircuitBuilder.Singleton("SFX_Zipper02", () => AudioSFXConstant("Zipper02")); }
        public static AudioPort SFX_Zipper03 { get => CircuitBuilder.Singleton("SFX_Zipper03", () => AudioSFXConstant("Zipper03")); }
        public static AudioPort SFX_Zipper04 { get => CircuitBuilder.Singleton("SFX_Zipper04", () => AudioSFXConstant("Zipper04")); }
    }
}