using RRCGSource;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RRCGSource
{
    public class Audio : AnyObject
    {
        public static Audio SFX_Adequate { get; }
        public static Audio SFX_Amazing { get; }
        public static Audio SFX_BeamGunDrop { get; }
        public static Audio SFX_BeamGunPickup { get; }
        public static Audio SFX_Beep { get; }
        public static Audio SFX_BlueScores { get; }
        public static Audio SFX_BlueWins { get; }
        public static Audio SFX_BootUp { get; }
        public static Audio SFX_BowlingStrike { get; }
        public static Audio SFX_BowlingSweeper { get; }
        public static Audio SFX_BowlingThud { get; }
        public static Audio SFX_BroomHit01 { get; }
        public static Audio SFX_BroomHit02 { get; }
        public static Audio SFX_BroomPickup01 { get; }
        public static Audio SFX_BroomPickup02 { get; }
        public static Audio SFX_BroomSwing { get; }
        public static Audio SFX_BucketHit { get; }
        public static Audio SFX_ButtonDown { get; }
        public static Audio SFX_ButtonUp { get; }
        public static Audio SFX_Buzzer { get; }
        public static Audio SFX_BuzzerShort { get; }
        public static Audio SFX_CCCCannonFired { get; }
        public static Audio SFX_CCCCannonImpact { get; }
        public static Audio SFX_CCCCannonLit { get; }
        public static Audio SFX_CCCCannonballIncoming { get; }
        public static Audio SFX_CapturePointScore { get; }
        public static Audio SFX_CardDeal { get; }
        public static Audio SFX_CardShuffle { get; }
        public static Audio SFX_CardSlide { get; }
        public static Audio SFX_CardboardThud { get; }
        public static Audio SFX_CashRegister { get; }
        public static Audio SFX_Click { get; }
        public static Audio SFX_Coach1 { get; }
        public static Audio SFX_Coach2 { get; }
        public static Audio SFX_Coach3 { get; }
        public static Audio SFX_Coach4 { get; }
        public static Audio SFX_Coach5 { get; }
        public static Audio SFX_Coach6 { get; }
        public static Audio SFX_Coach7 { get; }
        public static Audio SFX_Coach8 { get; }
        public static Audio SFX_Coach9 { get; }
        public static Audio SFX_Coach10 { get; }
        public static Audio SFX_Collectible { get; }
        public static Audio SFX_ConsumableAppleBite { get; }
        public static Audio SFX_ConsumableCakeBite01 { get; }
        public static Audio SFX_ConsumableCakeBite02 { get; }
        public static Audio SFX_ConsumableCakeBite03 { get; }
        public static Audio SFX_ConsumablePizzaBite { get; }
        public static Audio SFX_ConsumablePopcornBite01 { get; }
        public static Audio SFX_ConsumablePopcornBite02 { get; }
        public static Audio SFX_ConsumableRootBeerGlug { get; }
        public static Audio SFX_CountdownStinger { get; }
        public static Audio SFX_CountdownTick { get; }
        public static Audio SFX_Cows { get; }
        public static Audio SFX_CrowdAww { get; }
        public static Audio SFX_CrowdCheer { get; }
        public static Audio SFX_CrowdLaughing { get; }
        public static Audio SFX_CrowdOoooo { get; }
        public static Audio SFX_CutlassHeavyEnemyHit01 { get; }
        public static Audio SFX_CutlassHeavyEnemyHit02 { get; }
        public static Audio SFX_CutlassHeavyEnemyHit03 { get; }
        public static Audio SFX_CutlassHit01 { get; }
        public static Audio SFX_CutlassHit02 { get; }
        public static Audio SFX_CutlassLightEnemyHit01 { get; }
        public static Audio SFX_CutlassLightEnemyHit02 { get; }
        public static Audio SFX_CutlassParry01 { get; }
        public static Audio SFX_CutlassParry02 { get; }
        public static Audio SFX_CutlassParry03 { get; }
        public static Audio SFX_CutlassPickup { get; }
        public static Audio SFX_CutlassSwing01 { get; }
        public static Audio SFX_CutlassSwing02 { get; }
        public static Audio SFX_CutlassSwing03 { get; }
        public static Audio SFX_DartHit { get; }
        public static Audio SFX_DefaultFoostep01 { get; }
        public static Audio SFX_DefaultFootstep02 { get; }
        public static Audio SFX_DefaultFootstep03 { get; }
        public static Audio SFX_DefaultFootstepProne01 { get; }
        public static Audio SFX_DefaultFootstepProne02 { get; }
        public static Audio SFX_DefaultJump { get; }
        public static Audio SFX_DiceRoll { get; }
        public static Audio SFX_Ding { get; }
        public static Audio SFX_DingDing { get; }
        public static Audio SFX_DiscHit { get; }
        public static Audio SFX_DodgeballBounce { get; }
        public static Audio SFX_DodgeballPlayerHit { get; }
        public static Audio SFX_Drawer { get; }
        public static Audio SFX_ElectronicsMove { get; }
        public static Audio SFX_ElectronicsWarmUp { get; }
        public static Audio SFX_Equipment { get; }
        public static Audio SFX_Explosion { get; }
        public static Audio SFX_Failure { get; }
        public static Audio SFX_Firework { get; }
        public static Audio SFX_FryingPanEnvironmentHit { get; }
        public static Audio SFX_FryingPanHit01 { get; }
        public static Audio SFX_FryingPanHit02 { get; }
        public static Audio SFX_FryingPanHit03 { get; }
        public static Audio SFX_FryingPanPickup { get; }
        public static Audio SFX_FryingPanSwing01 { get; }
        public static Audio SFX_FryingPanSwing02 { get; }
        public static Audio SFX_GTRoomClear { get; }
        public static Audio SFX_GameOn { get; }
        public static Audio SFX_GameOver { get; }
        public static Audio SFX_GameOverBell { get; }
        public static Audio SFX_GlassBreak01 { get; }
        public static Audio SFX_GlassBreak02 { get; }
        public static Audio SFX_Goal { get; }
        public static Audio SFX_Goats { get; }
        public static Audio SFX_GoldDropped { get; }
        public static Audio SFX_GoldPickup01 { get; }
        public static Audio SFX_GoldPickup02 { get; }
        public static Audio SFX_GolfClap { get; }
        public static Audio SFX_GoodGame { get; }
        public static Audio SFX_HeartbeatDown { get; }
        public static Audio SFX_HeartbeatUp { get; }
        public static Audio SFX_Henhouse { get; }
        public static Audio SFX_Hit { get; }
        public static Audio SFX_HolsterAttach { get; }
        public static Audio SFX_HolsterDetach { get; }
        public static Audio SFX_Horn { get; }
        public static Audio SFX_Horse { get; }
        public static Audio SFX_KOColaTabOpened { get; }
        public static Audio SFX_KioskButton { get; }
        public static Audio SFX_LaserTagCrit { get; }
        public static Audio SFX_LaserTagDamage { get; }
        public static Audio SFX_LaserTagDetonation { get; }
        public static Audio SFX_LaserTagNotification { get; }
        public static Audio SFX_LaserTagOut { get; }
        public static Audio SFX_LatchGrab { get; }
        public static Audio SFX_LiquidPour { get; }
        public static Audio SFX_MeleeHit { get; }
        public static Audio SFX_MenuClick01 { get; }
        public static Audio SFX_MenuClick02 { get; }
        public static Audio SFX_MetalClunk { get; }
        public static Audio SFX_MetalClunkLight { get; }
        public static Audio SFX_MetalCreak01 { get; }
        public static Audio SFX_MetalCreak02 { get; }
        public static Audio SFX_MicrophoneFeedback { get; }
        public static Audio SFX_MicrophoneTap { get; }
        public static Audio SFX_OarHit { get; }
        public static Audio SFX_OarSwing { get; }
        public static Audio SFX_PaintmineArm { get; }
        public static Audio SFX_PaintmineAttach { get; }
        public static Audio SFX_PaintmineDetonate { get; }
        public static Audio SFX_PaintmineTrip { get; }
        public static Audio SFX_PitchforkHeavyHit { get; }
        public static Audio SFX_PitchforkLightHit { get; }
        public static Audio SFX_PitchforkPickup { get; }
        public static Audio SFX_PitchforkSwing { get; }
        public static Audio SFX_PointBlip { get; }
        public static Audio SFX_PointCaptured { get; }
        public static Audio SFX_PokerChipClack { get; }
        public static Audio SFX_PoolBallEnterPocket { get; }
        public static Audio SFX_PoolBallHitsBall { get; }
        public static Audio SFX_PoolBallHitsCushion { get; }
        public static Audio SFX_PoolCueHitsBall { get; }
        public static Audio SFX_PoolCueHitsFloor { get; }
        public static Audio SFX_PowerMissileExplode { get; }
        public static Audio SFX_PowerMissileFire { get; }
        public static Audio SFX_PowerMissileImpact { get; }
        public static Audio SFX_Punch1 { get; }
        public static Audio SFX_Punch2 { get; }
        public static Audio SFX_RakeHeavyHit { get; }
        public static Audio SFX_RakeLightHit { get; }
        public static Audio SFX_RakePickup { get; }
        public static Audio SFX_RakeSwing { get; }
        public static Audio SFX_Rattlesnake { get; }
        public static Audio SFX_ReadyToStart { get; }
        public static Audio SFX_RedScores { get; }
        public static Audio SFX_RedWins { get; }
        public static Audio SFX_Revive { get; }
        public static Audio SFX_RezIn { get; }
        public static Audio SFX_Score { get; }
        public static Audio SFX_ShareCamCountdownTick { get; }
        public static Audio SFX_ShareCamPrint { get; }
        public static Audio SFX_ShareCamShutter { get; }
        public static Audio SFX_ShareCamSuccess { get; }
        public static Audio SFX_ShieldHit { get; }
        public static Audio SFX_ShovelBash01 { get; }
        public static Audio SFX_ShovelBash02 { get; }
        public static Audio SFX_ShovelHeavyHit { get; }
        public static Audio SFX_ShovelLightHit { get; }
        public static Audio SFX_ShovelPickup { get; }
        public static Audio SFX_ShovelSwing { get; }
        public static Audio SFX_SmallExplosion1 { get; }
        public static Audio SFX_SmallExplosion2 { get; }
        public static Audio SFX_SnareDrum { get; }
        public static Audio SFX_SoccerBallHeavy { get; }
        public static Audio SFX_SoccerBallHitHeavy { get; }
        public static Audio SFX_SoccerBallHitLight { get; }
        public static Audio SFX_Sparkle { get; }
        public static Audio SFX_Splash { get; }
        public static Audio SFX_Springboard { get; }
        public static Audio SFX_SqueakyFishEnvironmentHit { get; }
        public static Audio SFX_SqueakyFishHit01 { get; }
        public static Audio SFX_SqueakyFishHit02 { get; }
        public static Audio SFX_SqueakyFishHit03 { get; }
        public static Audio SFX_SqueakyFishHit04 { get; }
        public static Audio SFX_SqueakyFishPickup { get; }
        public static Audio SFX_SqueakyFishSwing01 { get; }
        public static Audio SFX_SqueakyFishSwing02 { get; }
        public static Audio SFX_StickyNote { get; }
        public static Audio SFX_StoolHit { get; }
        public static Audio SFX_StoolPickup { get; }
        public static Audio SFX_StoolShatter { get; }
        public static Audio SFX_StuntrunnerCountdown1 { get; }
        public static Audio SFX_StuntrunnerCountdown2 { get; }
        public static Audio SFX_StuntrunnerCountdown3 { get; }
        public static Audio SFX_StuntrunnerGetReady { get; }
        public static Audio SFX_StuntrunnerGo { get; }
        public static Audio SFX_SubsonicBoom { get; }
        public static Audio SFX_SwordEnvironmentHit { get; }
        public static Audio SFX_SwordHeavyEnemyHit { get; }
        public static Audio SFX_SwordShieldHit { get; }
        public static Audio SFX_TennisBallImpact { get; }
        public static Audio SFX_Thud { get; }
        public static Audio SFX_TieGame { get; }
        public static Audio SFX_TiresScreeching { get; }
        public static Audio SFX_ToggleButtonOFF { get; }
        public static Audio SFX_ToggleButtonON { get; }
        public static Audio SFX_TorchPickup { get; }
        public static Audio SFX_TorchSwing { get; }
        public static Audio SFX_TrainBell { get; }
        public static Audio SFX_TriggerMisfire { get; }
        public static Audio SFX_UILevelUp { get; }
        public static Audio SFX_UIScore01 { get; }
        public static Audio SFX_UIScore02 { get; }
        public static Audio SFX_UIScore03 { get; }
        public static Audio SFX_UIScore04 { get; }
        public static Audio SFX_UIXP01 { get; }
        public static Audio SFX_UIXP02 { get; }
        public static Audio SFX_UIXP03 { get; }
        public static Audio SFX_WalkieNotification { get; }
        public static Audio SFX_WallSmack { get; }
        public static Audio SFX_WatchButtonDown { get; }
        public static Audio SFX_WatchButtonUp { get; }
        public static Audio SFX_WatchOpen { get; }
        public static Audio SFX_WaterGulp { get; }
        public static Audio SFX_WaterSplash { get; }
        public static Audio SFX_WhipHeavyThrow { get; }
        public static Audio SFX_WhipLightThrow { get; }
        public static Audio SFX_WhipPickup { get; }
        public static Audio SFX_WhipPrime { get; }
        public static Audio SFX_WhipTraversalHooked { get; }
        public static Audio SFX_WhipTraversalTeleport { get; }
        public static Audio SFX_WhipCrackHeavy { get; }
        public static Audio SFX_WhipCrackLight01 { get; }
        public static Audio SFX_WhipCrackLight02 { get; }
        public static Audio SFX_Whistle01 { get; }
        public static Audio SFX_Whistle02 { get; }
        public static Audio SFX_WhistleDown { get; }
        public static Audio SFX_WhistleUp { get; }
        public static Audio SFX_Whoosh1 { get; }
        public static Audio SFX_Whoosh2 { get; }
        public static Audio SFX_YouWin { get; }
        public static Audio SFX_Zipper01 { get; }
        public static Audio SFX_Zipper02 { get; }
        public static Audio SFX_Zipper03 { get; }
        public static Audio SFX_Zipper04 { get; }
    }
}
