using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RRCG
{
    public class RRTypesUtils
    {
        // List of all implemented classes in RRCG
        public static HashSet<string> ImplemetedRRTypes = new HashSet<string>() {
            "AI",
            "Vector3",
            "Quaternion",
            "TriggerHandle",
            "WelcomeMat",
            "StudioObject",
            "AnalyticsPayload",
            "Player",
            "RecRoomObject",
            "Combatant",
            "PatrolPoint",
            "Audio",
            "AudioPlayer",
            "Consumable",
            "RoomKey",
            "BackgroundObjects",
            "Color",
            "Beacon",
            "Button",
            "CollisionData",
            "Costume",
            "DestinationRoom",
            "Die",
            "PlayerWorldUI",
            "RoomDoor",
            "Emitter",
            "ExplosionEmitter",
            "Fog",
            "HUDElement",
            "Reward",
            "GroundVehicle",
            "GunHandle",
            "HolotarProjector",
            "InteractionVolume",
            "InvisibleCollision",
            "LaserPointer",
            "Light",
            "Piston",
            "PlayerOutfitSlot",
            "ProjectileLauncher",
            "RemoteVideoPlayer",
            "PlayerSpawnPointV2",
            "Skydome",
            "Sun",
            "SunDirection",
            "Rotator",
            "Seat",
            "SFX",
            "Text",
            "ToggleButton",
            "MotionTrail",
            "TriggerVolume",
            "VectorComponent",
            "RoomCurrency",
            "HUDConstant",
            "SteeringEngine",
            "GiftDropShopItem",
            "ObjectiveMarker",
            "MeleeZone",
            "SwingHandle",
            "RoomLevelHUD",
            "Touchpad",
            "AnimationController",
            "InventoryItem",
            "State",
            "Grabber",
            "TextScreen",
            "EquipmentSlot",
            "DialogueUI",
            "CollisionDetectionVolume",
            "RoomOffer",
            "Handle",
            "RecNetImage",
            "RangedWeapon",
            "Storefront"
        };
    }
}
